all:
	LD_LIBRARY_PATH=/home/duke/dev/cpu-rtos/cpu/Python-3.12.13:$$LD_LIBRARY_PATH \
	./../.venv/bin/python run_main_test.py

# export LD_LIBRARY_PATH=/home/duke/dev/cpu-rtos/cpu/Python-3.12.13:$LD_LIBRARY_PATH